lbfm-rwth/GaussPar

subprograms.g
=> Add comments to ChopMatrix in subprograms.g

README.md, measure_contention.g, profiling.g
Fixes issue #14. Please merge.
=> Replace chopSize by numberChops

dependencies_main.g, main_full_par_trafo.g, read_hpc.g
Fixes issue #6. ~~Do not merge yet - WORK IN PROGRESS!~~ Please merge now. :)
=> Making ChiefParallel more readable

tasks.g
=> Fix ScheduleTask mock-up

main.g
Fixes #4. Please review.
What other checks should be done?
I thought about checking whether the height and width of the matrix matches the values of a and b. But why do we need a and b if we could check this by ourselves?
=> Add type checking of input to main function

.travis.yml, scripts/run_tests.sh
teststats.g contains the tests for the functions that do
the timing runs etc.
=> Add timing test to travis 

gap/main.g
This makes our output more similar to the output in the original gauss package.
=> Adds heads as a field to the result record

README.md, gap/dependencies_main.g, gap/main.g, gap/main.gd, gap/main.gi, gap/measure_contention.g, gap/stats/timing.g, init.g, read.g, tst/parallel/chiefparallel.tst, tst/parallel/echelon_form.tst, tst/standard/chief.tst, tst/standard/echelon_form.tst
Fixes issue #70 
Please review and/or merge.
=> Create wrapper functions

README.md, gpl-2.0.txt
=> Add license file

tst/parallel/special_matrices.tst, tst/standard/special_matrices.tst, tst/testdata/matrices.g, tst/testfunctions.g
Adds more test matrices in /tst/testdata/matrices.g for further evaluation.
=> More test matrices

gap/dependencies.g, read.g
Also adds an explaination what purpose the functions in this file
serve.
=> Rename dependencies_main.g to dependecies.g

gap/dependencies.g, gap/main.g
- converts tabs to 4 spaces everywhere
- deletes trailing whitespaces in gap/dependencies.g and gap/main.g
=> Clean up whitespace

gap/main.g, gap/subprograms.g
=> Use atomic list R in the parallel version

gap/main.g, gap/subprograms.g
destructive versions of subprograms.
use those in sequential version.
=> Cleardown destructive

gap/main.g, gap/measure_contention.g, tst/parallel/chiefparallel.tst, tst/parallel/echelon_form.tst, tst/standard/chief.tst, tst/standard/echelon_form.tst, tst/testfunctions.g
Return the negative of coeffs and vectors and adapt test files.
Fixes #94 .
=> Change output of Chief to match Gauss Package

gap/main.g
=> Remove usage of dummy tasks in main.g

gap/main.g, gap/subprograms.g
I haven't reviewed the changes yet.
=> Some fixes by jendrik

tst/parallel/chiefparallel.tst, tst/parallel/echelon_form.tst, tst/parallel/special_matrices.tst, tst/standard/chief.tst, tst/standard/echelon_form.tst, tst/standard/special_matrices.tst, tst/testfunctions.g
Creates new functions in tst/testfunctions.g that combine the
content of the previously similar test files.
Fixes #115 
=> Combine content of test files to avoid duplication

gap/subprograms.g
=> Remove debugging statement in Extend_destructive

tst/parallel/chiefparallel.tst, tst/parallel/echelon_form.tst, tst/parallel/special_matrices.tst, tst/standard/chief.tst, tst/standard/echelon_form.tst, tst/standard/main.tst, tst/standard/rref.tst, tst/standard/special_matrices.tst, tst/standard/verify.tst, tst/stats/certain_specs.tst, tst/stats/measure-contention.tst, tst/stats/timing.tst
by resetting the global state with `START_TEST` and `STOP_TEST`.
This is how I understood https://www.gap-system.org/Manuals/doc/ref/chap7.html.
Fixes #152 .
Please review.
=> Make randomized tests reproducible

gap/main.g, gap/subprograms.g
Fixes #153 .
I spent a long time thinking about whether or how to combine the two functions, but although they are very similar they also differ in a few parts. It seems a waste of time to combine them.
Please just approve and merge :P
=> Add functions for glueing M, R and K

gap/thread-local.g
have to return ReadOnly or Immutable Objects. All
statements of the form
'return MakeReadOnlyOrImmutableObj(...)'
are replaced by
'retrun ...'
=> Thread local functions (like CEX,REX,...) do not..

gap/thread-local.g
Optimze/Clean up all functions in thread-local.g except CEX and REX.
=> Optimize/Clean up code in thread-local.g

gap/dependencies.g, gap/main.gi
to manage dependencies, where GAUSS_ClearUpDependencies is a new
function following our overall design for handling dependencies.
=> Step 3 now uses GAUSS_ClearUpDependencies

.travis.yml, gap/upstream.g, read.g, tst/sequential/echelonbasismutable.tst, tst/testall.g
A version to work with the cvec pkg.
=> Add EchelonBasisMutableT

gap/main.gi, gap/utils.g
=> Remove result.transformation from DoEchelon... return args

gap/thread-local.g, gap/utils.g
=> Use compressed identity matrices everywhere
