- read.g
- read_hpc.g
- timing.g
This reverts commit d847260c45a20c420a387e8695ecc6efc0c53d66.
I deleted `timing.g` since I thought we don't it anymore. But it is still used in `measure_contention.g`.
> Revert "Get rid of IO pkg and timing.g"

- measure_contention.g
- tst/parallel/measure.tst
Should fix issue #27 and #45.
After reading a lot in the documentation I decided to call the main function in measure_contention.g MeasureContention to follow the usual naming convention. I am not sure whether this is the correct thing to do.
I am also not quite happy about the `options...` argument for MeasureContention. In the documentation I saw something like `MeasureContention := function(numberChops, q, A : visible)` where `visible`would be optional. This version was what I would have preferred. Unforunately I lost the page and couldn't find it again.
> Measure 27

- read.g
This makes `tasks.g` to be read before `main.g`.
Otherwise reading `main.g` prints lots of syntax warnings that
`ScheduleTask` is not bound.
> Fix read.g

- scripts/run_tests.sh
- tst/testall.g
That file calls teststandard.g or
testparallel.g and teststats.g depending on whether
HPCGAP or GAP is used.
> Use a single tst/testall.g for travis

- gap/timing.g
Fixes a bug: calling the function with values smaller then 10 lead
to rounding to the first digit. E.g. the result with `2.61` was
`2.`.
> Fix threeSignificantDigits

- tst/parallel/special_matrices.tst
- tst/standard/special_matrices.tst
- tst/testdata/matrices.g
- tst/testfunctions.g
Adds the test files tst/parallel/special_matrices.tst and tst/standard/special_matrices.tst where tests for special matrices are executed. Those special matrices are stored in tst/testdata/matrices.g and there is a new file tst/testfunctions.g for functions that are for usage in tests only.
Fixes #62, please merge.
> Broaden use of RandomEchelonMat in tests

- gap/dependencies_main.g
- gap/main.g
Instead of passing them as a list, we pass them as a record.
> Rewrite how parameters are passed to UpdateRow

- gap/dependencies_main.g
- gap/main.g
- gap/stats/timing.g
- gap/timing.g
- init.g
- read.g
- tst/testall.g
- tst/testparallel.g
- tst/teststandard.g
- tst/teststats.g
Add code to `tst/test*.g` files to set the info level to 0.
Also makes the output less verbose for the info level 1, and
a hint that the package still is in early stage is printed.
Fixes #82.
> Set info level to one while the pkg is still alpha

- README.md
- gap/main.gi
- gap/measure_contention.g
- gap/stats/timing.g
- tst/parallel/chiefparallel.tst
- tst/parallel/echelon_form.tst
- tst/parallel/special_matrices.tst
- tst/standard/chief.tst
- tst/standard/echelon_form.tst
- tst/standard/special_matrices.tst
- tst/testfunctions.g
Change the arguments of DoEchelonMatTransformationBlockwise
and adapt the corresponding tests.
Also fixes the `heads` component in the return value of
DoEchelonMatTransformationBlockwise.
Fixes #93. Fixes #85.
> Do...Blockwise: Change variadic arg to a record

- gap/overload-hpcgap-functions-in-gap.g
- read.g
MakeReadOnlyObj does nothing in GAP. We want it to make its argument
immutable.
Also rename gap/tasks.g.
> Overwrite MakeReadOnlyObj, define RegionOf in GAP

- gap/main.g
- gap/subprograms.g
Also changes R[i,j] in GAUSS_ClearUp_destructive to R[i][j] due to
problems with the new syntax in hpcgap
> Turn R into FixedAtomicList

- gap/echelon_form.g
- gap/stats/timing.g
- tst/parallel/echelon_form.tst
- tst/standard/echelon_form.tst
- tst/testfunctions.g
Changes name to GAUSS_RandomMatFromEchelonForm and reduces the number of arguments.
Fixes #90 .
> Clean up GAUSS_shapelessMat

- gap/subprograms.g
Rename to `GAUSS_MKR` in gap/subprograms.g
Fixes #106 .
> Rename function `MKR` to fit naming conventions

- gap/subprograms.g
Also fixes a small bug in CEX, see a0dee27.
> Make return values of all low-lvl functions read-only

- gap/main.g
- gap/main.gi
Adapts the global functions `EchelonMatBlockwise` and `EchelonMatTransformationBlockwise`
to the changes in `DoEchelonMatTransformationBlockwise` (namely that
`DoEchelonMatTransformationBlockwise` needs two arguments now).
And fixes the comment in `Chief` which described the usage of the arguments wrongly.
> Fixes fault in the global functions and a comment

- gap/overload-hpcgap-functions-in-gap.g
- gap/subprograms.g
Reverts the change to MakeReadOnlyObj that lets it make its argument immutable (see 3b27590).
Also fixes and simplifies ClearUp.
> Fix ClearUp and revert change to MakeReadOnlyObj

- gap/RREF.g
- read.g
- tst/standard/rref.tst
- tst/testall.g
- tst/testdata/rref.g
Taking http://mathonline.wikidot.com/reduced-row-echelon-form-of-a-matrix-rref
as an inspiration this commit adds a function that checks whether a matrix
is in RREF and the corresponding tests.
Fixes #101 
> New function to check whether matrix is in RREF

- gap/main.g
The dimensions of TaskListClearDown, TaskListUpdateR and TaskListUpdateM
where mixed up. Running DoEchelonMatTransformationBlockwise with a !=b
threw an error. This has been fixed.
> Fixes a bug in the initialisation

- gap/main.g
- gap/main.gi
Chief has now a new argument "withTrafo". If set to false,
all steps to compute the transformation will be ommited.
> Add version that does not compute the trafo.

- gap/main.g
- gap/main.gi
- read.g
- tst/standard/verify.tst
Checks whether the result, that you get through applying the transformation
matrix to the matrix, is in RREF. If not than the algorithm is not correct
and an error is raised.
Also raises an error if the result should be verified but the
transformation matrix won't be computed.
> Verify output via transformation matrix in Chief

- gap/main.g
- gap/main.gd
- gap/subprograms.g
Older versions of HPC-GAP still place guards correctly. These uncover some places where we were writing into read-only objects by accident.
I may have fixed these issues, but IMO we should write down some design principles and make sure that all functions respect these, see #166 and #168. In particular I have tried to find all places where compressed matrices, in `Is8BitMatrixRep`, silently get converted back to lists of lists.
This also uncovers a bug which I suspect to be responsible for the crashes in our rewrite of the main routine, see #163. The bug can now be reproduced under GAP, see the last commit 453b763.
> Run master under an older version of HPC-GAP

- tst/parallel/special_matrices.tst
- tst/testfunctions.g
Fixes issue #230 .
Short explanation:
Matrix M9, which is a row vector, was multiplied by a 100x100 matrix and then analysed by EchelonMatTransformation(Blockwise). Obviously the comparison with M9 didn't work in the end. Same thing for M10 and M11.
> Solve bug that led to testing errors with some special matrices
